[project]
name = "orchestrator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.122.0",
    "pydantic>=2.12.5",
    "redis>=7.1.0",
    "uvicorn>=0.38.0",
]
